In [91]:
import numpy as np
import pandas as pd

In [92]:
movies = pd.read_csv(r'E:\Coding\Learning to code\Machine Learning\RECOMMENDATION system\Movie Recommendation System\Datasets\tmdb_5000_credits.csv')
credits = pd.read_csv(r'E:\Coding\Learning to code\Machine Learning\RECOMMENDATION system\Movie Recommendation System\Datasets\tmdb_5000_movies.csv')

In [93]:
credits.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [94]:
movies.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [95]:
movies.shape

(4803, 4)

In [96]:
credits.shape

(4803, 20)

In [97]:
movies = movies.merge(credits,on='title')

In [98]:
movies.head(1)
# budget
# homepage
# id
# original_language
# original_title
# popularity
# production_comapny
# production_countries
# release-date(not sure)

,movie_id,title,cast,crew,budget,genres,homepage,id,keywords,original_language,...,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,vote_average,vote_count
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,...,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,7.2,11800

In [99]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   movie_id              4809 non-null   int64
 1   title                 4809 non-null   str
 2   cast                  4809 non-null   str
 3   crew                  4809 non-null   str
 4   budget                4809 non-null   int64
 5   genres                4809 non-null   str
 6   homepage              1713 non-null   str
 7   id                    4809 non-null   int64
 8   keywords              4809 non-null   str
 9   original_language     4809 non-null   str
 10  original_title        4809 non-null   str
 11  overview              4806 non-null   str
 12  popularity            4809 non-null   float64
 13  production_companies  4809 non-null   str
 14  production_countries  4809 non-null   str
 15  release_date          4808 non-null   str
 16  revenue               4809 non-null   int64
 17  runtime               4807 non-null   float64
 18  spoken_languages      4809 non-null   str
 19  status                4809 non-null   str
 20  tagline               3965 non-null   str
 21  vote_average          4809 non-null   float64
 22  vote_count            4809 non-null   int64
dtypes: float64(3), int64(5), str(15)
memory usage: 864.2 KB

In [100]:
movies['original_language'].value_counts() # will remove

original_language
en    4510
fr      70
es      32
zh      27
de      27
hi      19
ja      16
it      14
ko      12
cn      12
ru      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
ta       2
cs       2
ar       2
id       2
ro       2
te       1
xx       1
hu       1
is       1
tr       1
nb       1
af       1
pl       1
vi       1
ky       1
no       1
sl       1
ps       1
el       1
Name: count, dtype: int64

### Decided not to keep these features:
* budget
* homepage
* id
* original_language
* original_title
* popularity
* production_comapny
* production_countries
* release-date(not sure)

In [101]:

movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [102]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   str
 2   overview  4806 non-null   str
 3   genres    4809 non-null   str
 4   keywords  4809 non-null   str
 5   cast      4809 non-null   str
 6   crew      4809 non-null   str
dtypes: int64(1), str(6)
memory usage: 263.1 KB

### Target to finalize the dataframe as:

movie_id | title | tags


to do these, we merge some columns

### But lets first to basic Data Preprocessing

In [103]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [104]:
movies.dropna(inplace=True)

In [105]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [106]:
movies.duplicated().sum()

np.int64(0)

In [107]:
movies.iloc[0].genres

## fix this weird dictionary into :-
# ['Action', 'Adventure', 'Fantasy', 'Scifi']

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [108]:
## HELPER Function
import ast
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [109]:
movies.dropna(inplace=True)

In [110]:
movies['genres'] = movies['genres'].apply(convert)

In [111]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [112]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [113]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [114]:
movies['cast'] = movies['cast'].apply(convert)
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [115]:
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])

In [116]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [117]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [118]:
# movies['overview'] = movies['overview'].apply(lambda x:x.split())
movies.sample(5)

,movie_id,title,overview,genres,keywords,cast,crew
1184,6073,The Mexican,"Jerry Welbach, a reluctant bagman, has been gi...","[Action, Comedy, Crime, Romance]","[kidnapping, pistol]","[Brad Pitt, Julia Roberts, James Gandolfini]",[Gore Verbinski]
3434,4836,Layer Cake,When a seemingly straight-forward drug deal go...,"[Drama, Thriller, Crime]","[kidnapping, ecstasy, drug traffic, drug mule,...","[Daniel Craig, Tom Hardy, Colm Meaney]",[Matthew Vaughn]
2049,30379,Megiddo: The Omega Code 2,Stone (the Antichrist) becomes President of th...,"[Action, Science Fiction, Thriller]",[dystopia],"[Michael York, Michael Biehn, Diane Venora]","[Brian Trenchard-Smith, Paul J. Lombardi]"
1413,11979,Queen of the Damned,Lestat de Lioncourt is awakened from his slumb...,"[Drama, Fantasy, Horror]","[queen, rock star, secret society, vampire, li...","[Stuart Townsend, Aaliyah, Marguerite Moreau]",[Michael Rymer]
1111,834,Underworld: Evolution,As the war between the vampires and the Lycans...,"[Fantasy, Action, Science Fiction, Thriller]","[budapest, key, vampire, light, werewolf, evol...","[Kate Beckinsale, Scott Speedman, Tony Curran]",[Len Wiseman]

In [119]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [120]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [121]:

movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]

In [122]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [123]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [124]:
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])
#new.head()

In [125]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [126]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [127]:
vector = cv.fit_transform(new['tags']).toarray()

In [128]:

vector.shape

(4806, 5000)

In [129]:

from sklearn.metrics.pairwise import cosine_similarity

In [130]:

similarity = cosine_similarity(vector)

In [131]:

similarity

array([[1.        , 0.08858079, 0.05905386, ..., 0.02478408, 0.02599376,
        0.        ],
       [0.08858079, 1.        , 0.06451613, ..., 0.02707652, 0.        ,
        0.        ],
       [0.05905386, 0.06451613, 1.        , ..., 0.02707652, 0.        ,
        0.        ],
       ...,
       [0.02478408, 0.02707652, 0.02707652, ..., 1.        , 0.07150969,
        0.0489116 ],
       [0.02599376, 0.        , 0.        , ..., 0.07150969, 1.        ,
        0.05129892],
       [0.        , 0.        , 0.        , ..., 0.0489116 , 0.05129892,
        1.        ]], shape=(4806, 4806))

In [132]:

new[new['title'] == 'The Lego Movie'].index[0]

np.int64(744)

In [133]:
def recommend(movie):
    index = new[new['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new.iloc[i[0]].title)

In [134]:

recommend('Gandhi')

Gandhi, My Father
The Wind That Shakes the Barley
A Passage to India
Guiana 1838
Ramanujan